# Define required macros here
 SHELL = /bin/sh

 OBJS =  ../src/*.cpp
 CFLAG = -O3
 CC = g++
 INCLUDE =
 LIBS = -lncursesw

 console_sudoku:${OBJ}
	${CC} ${CFLAG} ${INCLUDES} -o ../$@ ${OBJS} ${LIBS}
